### PR TITLE
:rocket: (Build): BUILD: update dockerfile

### LINKED ISSUE #204: BUILD: update Dockerfile
add github labels

### PR DESCRIPTION
**Pull request by ushiii111798**
add github related labels
temporary added yarn dev instead of build and start

closed #204

### CODE REVIEW

**Review by aggie97 — APPROVED** [review]

**Review by aggie97 — DISMISSED** [review]
고생하셨습니다.

**Review by aggie97 — APPROVED** [review]
왜 approve 안되나고

**Review by aggie97 — APPROVED** [review]
리뷰 재시도

**Review by daeuneeee — APPROVED** [review]
렛츠고

**Pull request merged**
